import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Assembles the Jekyll source of the documentation site (docs/site.md) in [outputDir] without
 * copying any text into the repository: the files of `site/` (configuration, group pages), every
 * `docs/NAME.md`, and `README.md` as `index.md` with the home page's front matter. Links between
 * documents are rewritten for the flat page layout by [DocsLinks]; a link that cannot be resolved
 * fails the build. A generated `_config.generated.yml` carries the version and, when they exist,
 * the logo, dark logo and favicon from `branding/`.
 */
abstract class PrepareJekyllSource : DefaultTask() {
    /** The documents and site files (declared so that a change reruns the task). */
    @get:InputFiles @get:PathSensitive(PathSensitivity.RELATIVE) abstract val sourceFiles: ConfigurableFileCollection

    /** Repository root; documents are read from it and repository links are checked against it. */
    @get:Internal abstract val root: DirectoryProperty

    @get:Input abstract val repository: Property<String>

    @get:Input abstract val branch: Property<String>

    @get:Input abstract val version: Property<String>

    /** The commit being built, shown in the footer; empty for a local build. */
    @get:Input @get:Optional abstract val commit: Property<String>

    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    init {
        // Links to repository files that are not pages depend on the files present, not only on the
        // declared inputs, and the assembly is fast.
        outputs.upToDateWhen { false }
    }

    @TaskAction
    fun assemble() {
        val base = root.get().asFile
        val sources = DocsLinks.sources(base)
        val problems = mutableListOf<String>()
        val rewritten = sources.mapValues { (path, text) ->
            DocsLinks.validate(path, text, problems)
            DocsLinks.rewrite(path, DocsLinks.splitFrontMatter(text).second, sources, repository.get(), branch.get(), { exists(base, it) }, problems)
        }
        if (problems.isNotEmpty()) {
            throw GradleException(problems.joinToString("\n", prefix = "The documentation has problems:\n") { "  - $it" })
        }
        val out = outputDir.get().asFile
        out.deleteRecursively()
        base.resolve("site").copyRecursively(out)
        out.resolve("Gemfile").delete()
        out.resolve("Gemfile.lock").delete()
        for ((path, text) in sources) {
            val head = if (path == "README.md") HOME_FRONT_MATTER else DocsLinks.splitFrontMatter(text).first
            out.resolve(DocsLinks.pageName(path)).writeText(head + rewritten.getValue(path))
        }
        val config = StringBuilder("# Generated by the prepareJekyllSource task.\n")
        config.append("axiom_version: \"").append(version.get()).append("\"\n")
        commit.orNull?.takeIf { it.isNotBlank() }?.let { config.append("axiom_commit: \"").append(it.take(40)).append("\"\n") }
        // README.md refers to branding/logo.svg, so the files keep their path in the site.
        base.resolve("branding").takeIf { it.isDirectory }?.copyRecursively(out.resolve("branding"))
        for ((key, name) in listOf("logo" to "logo.svg", "logo_dark" to "logo-dark.svg", "favicon_svg" to "favicon.svg")) {
            if (out.resolve("branding/$name").isFile) config.append(key).append(": \"/branding/").append(name).append("\"\n")
        }
        out.resolve("_config.generated.yml").writeText(config.toString())
        // An optional custom domain file, added to docs/ only when the owner decides (docs/site.md).
        base.resolve("docs/CNAME").takeIf { it.isFile }?.copyTo(out.resolve("CNAME"))
    }

    private fun exists(base: java.io.File, path: String): Int {
        val file = base.resolve(path)
        return if (file.isFile) 1 else if (file.isDirectory) 2 else 0
    }

    companion object {
        const val HOME_FRONT_MATTER = "---\ntitle: Home\nnav_order: 1\npermalink: /\n---\n\n"
    }
}
